# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
